config/routes.rb
Rails.application.routes.draw do
  resources :posts

  resources :posts do
    resources :comments, :only => [:create]
  end

  get 'users/index'
  post 'users/index' => 'posts#create'
  post 'users/content' => 'comments#create'
  get 'users/content'

  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(post_params)
    redirect_to controller: 'users', action: 'index'
  end

  private
    def post_params
      params.require(:comment).permit(:opinion)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts/new
  def new
  end

  def create
    @post = Post.new(post_params)
    @post.fav = 0
    @post.save
    redirect_to @post
  end

  def show
    @post = Post.find(params[:id])
    redirect_to root_path
  end

  def edit
    @post = Post.find(params[:id])
    @post.increment(:fav)
    @post.save
    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:text)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @posts = Post.all
  end

  def content
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def like
    @post = Post.find(params[:id])
    @post.increment(:fav)
    @post.save
    redirect_to controller: 'user', action: 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Samblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/new.html.erb
<h1>Mini Brog</h1>
<%= form_for :post, url: posts_path do |f|%>
  <p>
    <%= f.label :text, "件名" %>
    <%= f.text_field :text %>
    <%= f.submit "投稿" %>
  </p>
<% end %>

<hr>

app/views/users/content.html.erb
<h1>Mini Brog ver 2.1</h1>
<p><%= link_to '戻る', users_index_path%></p>

<hr>
<p> No.<%= @post.id %>: 投稿時間:<%= @post.created_at  %> | いいね:<%= @post.fav %> </p> 
<p> <%= @post.text%> </p> <br>

<%= form_for [@post, @comment] do |f| %>
  <p>
    <%= f.label :opinion, "コメント:" %>
    <%= f.text_field :opinion %>
    <%= f.submit "投稿"%>
  </p>
<% end %>

<hr>
<h2>コメント</h2>
<%= @post.comments.each.reverse_each do |comment| %>
  <p> <%= comment.opinion %> | 投稿時間:<%= comment.created_at%></p> <br>
<% end %>

app/views/users/index.html.erb
<h1>Mini Brog ver 2.1</h1>
<%= form_for :post, url: users_index_path do |f| %>
  <p>
    <%= f.label :text, "件名:" %>
    <%= f.text_field :text %>
    <%= f.submit "投稿" %>
  </p>
<% end %>

<hr>
<%= @posts.each.reverse_each do |post| %>
  <p> No.<%= post.id %>: <%= post.text%> <%= link_to '[コメント]', controller:'users', action:'content', id: post.id  %> </p> 
  <p> 投稿時間:<%= post.created_at %> | <%= link_to 'いいね', controller:'posts', action:'edit', id: post.id %> : <%= post.fav %>  | コメント:<%= post.comments.count %> </p> <br>

<hr width="75%">

<% end %>